(()=>{
const groups=[
["Sauces & condiments","https://shecookssheeats.co.uk/syns/category/sauce/",[["Apple Sauce","swips",1.0],["Balsamic Vinegar","swips",0.5],["Baxters Soup","swips",2.0],["BBQ Sauce","swips",1.0],["Blue Dragon Sauces","swips",1.0],["Brown Sauce","swips",0.5],["Caesar Dressing","swips",2.5],["Campbells Condensed Soup","swips",3.0],["Colmans Sauce Mixes","swips",1.75],["Cranberry Sauce","swips",1.5],["Fish Sauce","free",null],["Gravy (Bisto made up)","swips",1.0],["Green Pesto","swips",3.0],["Guacamole","swips",2.5],["Hoisin Sauce","swips",1.5],["Hollandaise Sauce","swips",3.5],["Hummus","swips",2.5],["Light Mayonnaise","swips",1.5],["Light Salad Cream","swips",1.0],["Mayonnaise","swips",3.5],["Mint Sauce","swips",0.5],["Miso Paste","swips",0.5],["Oyster Sauce","swips",0.5],["Pasta Sauce (Jar)","swips",2.0],["Red Pesto","swips",2.5],["Salad Cream","swips",1.5],["Soy Sauce","free",null],["Sriracha","swips",0.5],["Stock Cube","free",null],["Sweet Chilli Sauce","swips",1.0],["Tahini","swips",4.0],["Tartare Sauce","swips",2.0],["Tomato Ketchup","swips",1.0],["Tomato Puree","free",null],["Tzatziki","swips",1.0],["Wine Vinegar","free",null],["Worcestershire Sauce","free",null]]],
["Chilled","https://shecookssheeats.co.uk/syns/category/dairy/",[["Benecol Yogurt Drink","swips",2.0],["Brie","swips",3.5],["Camembert","swips",3.0],["Cheddar Cheese","healthy_extra",null],["Cheese","swips",7.5],["Condensed Milk","swips",3.0],["Cottage Cheese","swips",1.5],["Creme Fraiche","swips",2.5],["Creme Fraiche Half Fat","swips",1.0],["Custard","swips",3.5],["Double Cream","swips",3.5],["Elmlea Double Alternative","swips",2.5],["Evaporated Milk","swips",6.0],["Feta Cheese","swips",3.0],["Greek Yogurt 0% Fat","free",null],["Halloumi","swips",3.5],["Mozzarella","swips",2.5],["Muller Corner Yogurt","swips",7.0],["Parmesan","swips",2.5],["Ricotta","swips",1.5],["Single Cream","swips",2.5],["Soured Cream","swips",1.5],["Vanilla Ice Cream","swips",4.5],["Whipping Cream","swips",3.0]]],
["Packets & cupboard","https://shecookssheeats.co.uk/syns/category/cereal/",[["All-Bran","healthy_extra",null],["Bran Flakes","swips",3.0],["Cheerios","swips",3.0],["Chia Seeds","swips",2.0],["Cornflakes","swips",3.0],["Crunchy Nut Cornflakes","swips",3.5],["Frosties","swips",3.5],["Granola","swips",8.0],["Muesli","swips",5.0],["Oat Bran","healthy_extra",null],["Oatibix","healthy_extra",null],["Rice Krispies","swips",3.0],["Semolina","swips",2.5],["Shredded Wheat","healthy_extra",null],["Shreddies","swips",3.5],["Special K","swips",3.0]]],
["Drinks","https://shecookssheeats.co.uk/syns/category/drink/",[["Almond Milk Unsweetened","swips",1.0],["Apple Juice","swips",2.0],["Cadbury Hot Chocolate Powder","swips",4.0],["Cappuccino","swips",2.5],["Chai Latte","swips",5.0],["Coconut Water","swips",2.5],["Coffee","swips",0.0],["Energy Drink","swips",3.0],["Fruit Cordial","swips",1.0],["Grape Juice","swips",2.5],["Hot Chocolate with Full Fat Milk","swips",7.0],["Huel","swips",10.0],["Latte (Semi-Skimmed)","swips",3.0],["Lemsip and Cold Remedy Sachets","swips",1.5],["Oat Milk","swips",5.0],["Options Hot Chocolate","swips",2.0],["Orange Juice","swips",2.0],["Protein Powder","swips",4.5],["SlimFast Shake","swips",7.5],["Smoothie","swips",3.0]]],
["Snacks & sweets","https://shecookssheeats.co.uk/syns/category/snack/",[["Breadsticks","swips",3.5],["Crackers","swips",3.5],["Cream Crackers","swips",3.0],["Doritos Cool Original","swips",7.5],["Flapjack","swips",13.0],["Nature Valley Bar","swips",10.0],["Oatcakes","swips",3.5],["Plain Popcorn","swips",3.0],["Plain Rice Cakes","swips",1.0],["Pretzels","swips",5.0],["Quavers","swips",3.5],["Ritz Crackers","swips",4.0],["Salted Popcorn","swips",4.0],["Skips","swips",3.5],["Snack-a-Jacks","swips",5.0],["Sweet Popcorn","swips",5.5],["Tortilla Chips","swips",7.0],["Twiglets","swips",5.0],["Wotsits","swips",4.0]]],
["Snacks & sweets","https://shecookssheeats.co.uk/syns/category/treat/",[["Apple Crumble","swips",14.0],["Bounty","swips",6.5],["Bread and Butter Pudding","swips",11.0],["Cheesecake","swips",16.0],["Chocolate Brownie","swips",10.0],["Chocolate Eclair","swips",9.0],["Chocolate Muffin","swips",17.0],["Cornetto Ice Cream","swips",8.5],["Creme Brulee","swips",9.0],["FAB Ice Lolly","swips",4.5],["Ice Cream","swips",6.0],["Jam Doughnut","swips",12.0],["Lemon Sorbet","swips",4.0],["Lotus Biscoff Biscuit","swips",2.0],["Magnum Classic Ice Cream","swips",12.0],["Maltesers","swips",0.5],["Profiteroles","swips",8.5],["Reeces Peanut Butter Cups","swips",5.5],["Ring Doughnut","swips",9.0],["Solero Ice Lolly","swips",5.0],["Tiramisu","swips",10.0],["Trifle","swips",9.0],["Vanilla Soft Serve","swips",5.0],["Victoria Sponge","swips",12.0]]],
["Sauces & condiments","https://shecookssheeats.co.uk/syns/category/spread/",[["Agave Syrup","swips",1.5],["Almond Butter","swips",4.5],["Biscoff Spread","swips",3.0],["Black Treacle","swips",1.5],["Cashew Butter","swips",4.5],["Golden Syrup","swips",1.5],["Jam","swips",1.0],["Lemon Curd","swips",1.5],["Maple Syrup","swips",1.5],["Marmalade","swips",1.0],["Marmite","free",null],["Nutella","swips",3.0],["Peanut Butter","swips",4.5],["Sugar","swips",1.0],["Vegemite","free",null]]],
["Chilled","https://shecookssheeats.co.uk/syns/category/meat/",[["Bacon","swips",1.5],["Battered Fish","swips",9.0],["Black Pudding","swips",3.0],["Chicken Kiev","swips",8.0],["Chorizo","swips",5.0],["Fish Cakes","swips",7.0],["Fish Fingers","swips",4.5],["Fridge Raiders","swips",3.5],["Frozen Chicken Nuggets","swips",8.0],["Ham","free",null],["Hot Dog (Frankfurter)","swips",3.0],["Pastrami","swips",1.0],["Pepperoni","swips",5.5],["Pork Pie","swips",8.0],["Pork Sausages","swips",6.0],["Prawn Crackers","swips",6.0],["Salami","swips",5.0],["Sausage Roll","swips",8.0],["Scampi","swips",8.0],["Scotch Egg","swips",10.0],["Streaky Bacon","swips",2.0],["Tinned Mackerel","free",null]]],
["Drinks","https://shecookssheeats.co.uk/syns/category/alcohol/",[["Ale","swips",5.0],["Amaretto","swips",3.5],["Baileys Irish Cream","swips",3.5],["Beer (Lager)","swips",5.5],["Champagne","swips",3.5],["Dry Cider","swips",4.0],["Dry Sherry","swips",2.5],["Gin","swips",2.5],["Lager","swips",4.5],["Pimms No.1","swips",2.0],["Port","swips",4.0],["Prosecco","swips",3.0],["Red Wine","swips",3.0],["Rose Wine","swips",3.0],["Rum","swips",2.5],["Sambuca","swips",3.0],["Stout / Guinness","swips",6.0],["Sweet Cider","swips",5.0],["Vodka","swips",2.5],["Whisky","swips",2.5],["White Wine","swips",3.0]]]
];
const existing=new Set(allReferenceFoods.map(p=>(p.name+'|'+p.brand).toLowerCase()));
const added=[];
for(const [category,sourceUrl,items] of groups){for(const [name,status,value] of items){const key=(name+'|2026 reference').toLowerCase();if(existing.has(key))continue;existing.add(key);added.push({id:'ref26-'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,brand:'2026 reference',category,kcal:null,portion:'primary listed portion — see source',emoji:'📚',type:'reference-2026',source:'Current 2026 public reference',plan:{status,value:value==null?null:Number(value),sourceUrl,sourceLabel:'Current independent 2026 category reference',confidence:'current-secondary',asOf:'2026',note:'Use the linked source for the exact primary portion; recipes and plan values can change.'}})}}
allReferenceFoods.push(...added);
if(typeof renderProducts==='function')renderProducts(allReferenceFoods,'Reference library',`${allReferenceFoods.length} built-in references • ${brandedFoods.length} current branded • ${historicalFoods.length} historical • ${added.length} added 2026 references`);
})();
